### ISSUE TITLE
Supplying manual variable weights to aoa doesn't work?

### ISSUE THREAD

**Issue by barbmuhling** [HannaMeyer/CAST#20]
Thank you for the great package!

I am attempting to run aoa without specifying a model (just newdata and weights). However, I'm getting the same results whether I supply a table of weights or not. Reading through the code, it seems as though if weight cannot be extracted from a trained model early on, it gets assigned as an object of class error, over-writing any table of weights initially supplied to the function. Do I have this right?

**Comment by daniel-althoff** [comment]
I experience the same issue.. couldn't figure a work around
