### ISSUE TITLE
What if remaining variables (VR) interact?

### ISSUE THREAD

**Issue by pecto2020** [HannaMeyer/CAST#32]
With reference to Algorithm 1 in Meyer et al., 2018.
If I have 4 predictors, Algorithm 1 evaluates all the possible couples to find the best one. 
The algorithm recursively adds the remaining variables i=3,4.
The algorithm stops if mean(error of model_i) > mean(error of model_best).
This means that if the error increases with 3 variables the algorithm stops and it doesn't check what happens whit 4.
What if there is a couple of remaining variables that interact and improve model performance? In other words,
what if with 3 variables performance decreases while with 4 variables it increases? If the algorithm stops at 3, we will never know.
Is that right or I'm missing something?

Thanks

**Comment by HannaMeyer** [comment]
That's right. If the 3rd variable alone has no relevance at all, then it will not be tested whether a combination with any 4th variable is relevant. An alternative is the "best subset selection" (CAST::bss) which is testing ALL possible combinations of variables.
But this is very very time consuming!
