### ISSUE TITLE
Tutorial 2 - AOA - csample function not defined

### ISSUE THREAD

**Issue by fmsabatini** [HannaMeyer/CAST#41]
Dear @HannaMeyer and colleagues, 
thanks for the nice package and clear tutorials. 
Please be aware that the csample function in the [tutorial 2](https://hannameyer.github.io/CAST/articles/cast02-AOA-tutorial.html) is not defined. I found it in the tutorial 3, but you might want to define it beforehand

**Comment by HannaMeyer** [comment]
Have a look in the Rmd. csample is defined there, it is just not shown in the html file.
I recommend going through the tutorial by using the Rmd file, not the html, because the html is intended here to explain and visualize the results while the Rmd contains all code needed to produce the results.
