### ISSUE TITLE
small glitch in man: `ffs()` instead of `train()`

### ISSUE THREAD

**Issue by tobwen** [HannaMeyer/CAST#5]
There's a glitch in https://github.com/HannaMeyer/CAST/blob/774293349d075249d809104f2204733915a04cfa/R/ffs.R#L102-L103

which generates
https://github.com/HannaMeyer/CAST/blob/774293349d075249d809104f2204733915a04cfa/man/ffs.Rd#L125-L126

I think you want `train()` instead of `ffs()` here.

**Comment by HannaMeyer** [comment]
Thanks, you're right.
