### ISSUE TITLE
Threshold calculated by `trainDI()` can become larger than the maximum training distance

### ISSUE THREAD

**Issue by dschlaep** [HannaMeyer/CAST#65]
Some sets of training distances produce thresholds that are larger than the maximum training distance.

I expected based on Meyer & Pebesma 2021 that the threshold would lie within the range of training distances:
> "The outlier-removed maximum DI of the training data is the one used as threshold for the AOA (boxplot in Figure 2b) where outliers are defined as values greater than the upper whisker (i.e. larger than the 75-percentile plus 1.5 times the IQR of the DI values of the cross-validated training data)."

Issue #46 and commit c92a3f2923545268db86e5bc1da6d8966d797d94 changed how this threshold is calculated.

Here two examples where the updated calculation produces a threshold value that is larger than the maximum training distance:
``` r
check_threshold <- function(di) {
  cat("max(di) = ")
  cat(
    max(di), 
    fill = TRUE
  )
  
  # threshold calculated by `trainDI()` with code from `CAST` <= `v0.7.0`
  cat("threshold <= v0.7.0: ")
  cat(
    max(di[!(di > (stats::quantile(di, 0.75) + 1.5 * stats::IQR(di)))])
  )
  cat("  ")
  cat(
    grDevices::boxplot.stats(di)$stats[5], 
    fill = TRUE
  )
  
  # threshold calculated by `trainDI()` with code from `CAST` >= `v0.7.1`
  #   * issue github.com/HannaMeyer/CAST/issues/46
  #   * commit https://github.com/HannaMeyer/CAST/commit/c92a3f2923545268db86e5bc1da6d8966d797d94
  cat("threshold >= v0.7.1: ")
  cat(
    stats::quantile(di, 0.75, na.rm = TRUE) + 1.5 * stats::IQR(di, na.rm = TRUE),
    fill = TRUE
  )
}

set.seed(17)
check_threshold(rpois(100, 2))
#> max(di) = 5
#> threshold <= v0.7.0: 5  5
#> threshold >= v0.7.1: 6

set.seed(17)
check_threshold(rnorm(100))
#> max(di) = 2.442327
#> threshold <= v0.7.0: 2.442327  2.442327
#> threshold >= v0.7.1: 2.560418
```

<sup>Created on 2023-06-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Meyer, H., & Pebesma, E. (2021). Predicting into unknown space? Estimating the area of applicability of spatial prediction models. Methods in Ecology and Evolution, 12(9), 1620–1633. https://doi.org/10.1111/2041-210X.13650

**Comment by HannaMeyer** [comment]
Thanks for finding this issue.  The threshold is now limited by the range of training distances.
